<a href="https://colab.research.google.com/github/omshahu/ML_Practicals/blob/main/IR_08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving diabetes_prediction_dataset - diabetes_prediction_dataset.csv to diabetes_prediction_dataset - diabetes_prediction_dataset (2).csv

In [ ]:
import pandas as pd

df = pd.read_csv("diabetes_prediction_dataset - diabetes_prediction_dataset.csv")
df.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0

In [ ]:
df['predicted_diabetes'] = df['HbA1c_level'].apply(lambda x: 1 if x > 6 else 0)

df[['HbA1c_level','diabetes','predicted_diabetes']].head()

   HbA1c_level  diabetes  predicted_diabetes
0          6.6         0                   1
1          6.6         0                   1
2          5.7         0                   0
3          5.0         0                   0
4          4.8         0                   0

In [ ]:
TP = len(df[(df['predicted_diabetes']==1) & (df['diabetes']==1)])
TN = len(df[(df['predicted_diabetes']==0) & (df['diabetes']==0)])
FP = len(df[(df['predicted_diabetes']==1) & (df['diabetes']==0)])
FN = len(df[(df['predicted_diabetes']==0) & (df['diabetes']==1)])

print("True Positive:", TP)
print("True Negative:",TN)
print("False Positive:", FP)
print("False Negative:", FN)

True Positive: 6490
True Negative: 60876
False Positive: 30624
False Negative: 2010

In [ ]:
TN = len(df[(df['predicted_diabetes']==0) & (df['diabetes']==0)])
accuracy = (TP + TN) / (TP + TN + FP + FN)

print("Accuracy:", accuracy)

Accuracy: 0.67366

In [ ]:
print("Accuracy Percentage:", round(accuracy*100,2), "%")

Accuracy Percentage: 67.37 %

In [ ]:
precision = TP / (TP + FP)
print("Precision:", precision)

Precision: 0.17486662714878481

In [ ]:
recall = TP / (TP + FN)
print("Recall:", recall)

Recall: 0.7635294117647059

In [ ]:
f1_score = 2 * (precision * recall) / (precision + recall)
print("F1 Score:", f1_score)

F1 Score: 0.28456175735519795

In [ ]:
print("\nEvaluation Metrics")

print("Precision :", round(precision,3))
print("Recall    :", round(recall,3))
print("F1 Score  :", round(f1_score,3))

Evaluation Metrics
Precision : 0.175
Recall    : 0.764
F1 Score  : 0.285